int main() {
    final string i = "ala ma kota";
    
    for (int i = 0; i < 10; i++) {
        print(i);
        i++;
    }

    print(i);

    for (final int i = 0; i < 10; i++) {
        // niedozwolone zmienianie wartości i w bloku pętli
        print(i);
    }

    for (i = 5 downto 0) {
        // niedozwolone zmienianie wartości i w bloku pętli,
        // a wartość końca pętli liczona tylko raz
        print(i);
    }

    return 0;
}
