int joljol() {
    int x = 5;
    return 128 + x;
}

int main() {
    int x = 5;
    int y = 2;
    // x = "aaaaa";
    // int y = "aaa"; error
    if (true) {
        string y = "aaa";
    }

    string i = "jol";
    // for (int i = 0; i < 10; i++) {
    //     print(i);
    // }
    // print(i);

    Array<int> jol = 10 ** [2];
    print(jol);
    jol[2] = 5;
    print(jol);
    print(joljol());

    for (final int i = 0; i < 20; i++) {
        print(i);
    }

    return 0;
}